apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string
  labels:
    app: random-string
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
      - name: random-string
        image: nitinnizhawan/random-string
        ports:
        - containerPort: 3000
