apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: randomstr
  name: randomstr-service
spec:
  selector:
    app: random-string
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000