apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-gateway-client
  namespace: non-gateway
  labels:
    app: non-gateway-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: non-gateway-client
  template:
    metadata:
      labels:
        app: non-gateway-client
    spec:
      containers:
      - name: non-gateway-client
        image: nnizhawanacr.azurecr.io/nnizhawan/request-maker:sha@sha256:02110da03ed50b86ebc2c6fc55d23a649d590b3c99bb366448616e68be7e9637
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "50m"
            memory: "90Mi"
        env:
        - name: URL
          value: "http://randomstr2.eastus.cloudapp.azure.com/"
        - name: isEgress
          value: "true"
        - name: nThreads
          value: "1"
        command: ["request-maker"]
        args: ["$(URL)", "$(isEgress)", "$(nThreads)"]
