apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: world2
  name: world2
spec:
  selector:
    app: hello-world
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000